#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from xmldiff.main import patch_command
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(patch_command())
