// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "9e937f56-e875-455b-b7da-7ffc3d2809a9");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1692581284);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1692581467);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{738e01e4-b982-48e9-b6b2-f2c921989a6a}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1692581280);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"413648301\":1692581427766,\"3686929620858940\":1692581427776,\"1348359415999805\":1692581427777}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"404116507\":[1692581427764,1692581466422]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{612596a3-f7be-41df-91a6-2ab36f8e66b9}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1692581281);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1692581284358");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1692602884358");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230605155639");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230605155639");
user_pref("browser.startup.homepage_override.mstone", "114.0");
user_pref("browser.startup.lastColdStartupCheck", 1692581466);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1692581281962");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "114.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ad1fd2b2eb354b8e9977a706c004767d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230605155639");
user_pref("extensions.lastAppVersion", "114.0");
user_pref("extensions.lastPlatformVersion", "114.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"18a9fb0d-0b65-43e3-8018-39310bbc5fd4\",\"pictureinpicture@mozilla.org\":\"42cd1251-8ff5-407f-90db-bfd28892c872\",\"screenshots@mozilla.org\":\"a6e22028-0315-4abd-b2b8-6710787cee03\",\"webcompat-reporter@mozilla.org\":\"df4692eb-47b0-4200-9d15-4125e9caf9a3\",\"webcompat@mozilla.org\":\"43604486-eb0c-4939-b2f3-1834024ff3ae\",\"default-theme@mozilla.org\":\"f8222b0f-1bab-4662-8657-093d226fed68\",\"addons-search-detection@mozilla.com\":\"d1b531d9-d23f-49a9-816c-86679b6ddcc1\",\"google@search.mozilla.org\":\"f8d2fa00-3931-4776-8c01-ebd3997133b3\",\"amazondotcom@search.mozilla.org\":\"83c64bee-f5de-4d4f-b2dc-ddc7094d7e4d\",\"wikipedia@search.mozilla.org\":\"1ffedcf9-dc0f-42ab-a076-25f1d14d9307\",\"bing@search.mozilla.org\":\"e03c24a8-a4a8-4892-910b-65bd233099f1\",\"ddg@search.mozilla.org\":\"9e8c868a-fe3e-49f6-96d6-a25d229bb21f\",\"ebay@search.mozilla.org\":\"766de763-0b79-40d8-9faf-7bf83bcb08b2\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.accessibilityCache", "{\"slug\":\"next-generation-accessibility-engine-powering-screen-readers\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"accessibilityCache\"},\"features\":null},\"active\":true,\"enrollmentId\":\"d38f3ee0-b9ce-491e-9231-d332ef6f6391\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Next generation accessibility engine powering screen readers\",\"userFacingDescription\":\"Evaluating a major re-architecture of Firefox's accessibility engine to improve performance of screen readers and other assistive technologies.\",\"lastSeen\":\"2023-08-21T01:28:02.209Z\",\"featureIds\":[\"accessibilityCache\"],\"prefs\":[{\"name\":\"accessibility.cache.enabled\",\"branch\":\"user\",\"featureId\":\"accessibilityCache\",\"variable\":\"enabled\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.accessibilityCache.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6410000e-6bac-40e8-ac14-fdfe939d1c65");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1692581465);
user_pref("toolkit.telemetry.cachedClientID", "c527260f-9fd6-4172-a4c3-0804778a4697");
user_pref("toolkit.telemetry.previousBuildID", "20230605155639");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
