#!/bin/sh

# Use neovim for vim if present.
if [ -x "$(command -v nvim)" ]
then 
    alias \
        vi="nvim" \
        vim="nvim" \
        vimdiff="nvim -d"
fi

# Start emacsclient
alias ee="emacsclient -c -a 'emacs'"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Alias true colors for tmux
alias tmux="TERM=screen-256color-bce tmux"

# Make firefox obey XDG
alias firefox=firefox --profile ~/.config/mozilla

# tmuxinator session manager
alias mux=tmuxinator

# monero wallet
alias monerod=monderod --data-dir "$XDG_DATA_HOME"/bitmonero

# xclip copy to clipboard
alias xcp="xclip -selection clipboard"

# Verbosity settings
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkdir="mkdir -pv"

# Colorize commands when possible
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" 

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
