#!/bin/zsh

# Source API secrets
#source $HOME/.config/shell/apikeys

#export $(xargs < $HOME/.config/shell/apikeys)

# Adds `~/.local/bin` to $PATH
#export PATH="$PATH:${$(find /usr/share/bin -type d -printf %p:)%%:}"

# Adds `/usr/share/bin` to $PATH
#export PATH="$PATH:/usr/share/bin/"

# Adds `/usr/share/bin` to $PATH
export PATH="$PATH:/usr/share/bin/"
export PATH="$PATH:$HOME/Scripts/"

# Add excite-cli to the path
export PATH="$PATH:$HOME/github_repos/excite-cli/excite"

# Add gunicorn to path
export PATH="$PATH:$HOME/.local/lib/python3.10/site-packages"
# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
#export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/.xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# Autostart x
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx "$XINITRC"
fi
