# Special key names available for modification:
# Up, Down, Left, Right, BSpace, BTab, DC (Delete), End, Enter, Escape, F1 to F20, Home, IC (Insert), NPage/PageDown/PgDn, PPage/PageUp/PgUp, Space, and Tab. 

# Prefix remap
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# General UI
set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g escape-time 0
set -g focus-events on
set -g allow-passthrough on
set -g extended-keys on
set -g extended-keys-format csi-u


set -g xterm-keys on
# Disable input delay in emacs.
set-option -s escape-time 0

set -g history-limit 50000

# Quick source
bind r source-file $HOME/.config/tmux/tmux.conf

# Clipboard
set -g set-clipboard on
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Pane resizing
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10

# Pane swapp
# Better splits
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# Window swapping
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Preserve path of the new window
bind c new-window -c "#{pane_current_path}"

# Toggle previous window
bind Space last-window

# Toggle last session
bind-key C-Space switch-client -l

# Add join pane command horizontally and vertically
bind b choose-window 'join-pane -h -s "%%"'
bind B choose-window 'join-pane -s "%%"'

# Kill panes, windows, and/or sessions without a prompt
bind-key BSpace kill-pane
bind-key DC kill-window
bind-key End kill-session

# Nuke all windows or sessions except current
bind -r Tab kill-window -a
bind -r IC kill-session -a

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'
set -g set-titles on
set -g set-titles-string '#h:#W'

# Theme
set -g status-style "fg=#ffffff,bg=black"
# set -g status-right "#[fg=yellow]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=yellow,bold] #I:#W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=yellow"
set -g message-style "bg=default,fg=yellow"
set -g message-command-style "bg=default,fg=yellow"
set -g mode-style "bg=yellow,fg=black"
setw -g clock-mode-colour yellow

# Status
# setw -g monitor-activity on
# set-window-option -g window-status-activity-style fg=white,bg=red,bold
# set-window-option -g window-status-bell-style fg=white,bg=red,bold
