#!/bin/sh

# Initialize settings
setxkbmap us &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.local/bin/monitors
setbg &
/usr/bin/emacs --daemon &
xsetroot -cursor_name left_ptr
autostart="mpd xcompmgr"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
