Player:
	Color: 5263E7
	CustomColors: 5163E7
	Name: Daddy
Game:
	IntroductionPromptVersion: 1
Sound:
Graphics:
Server:
	Map: e805f977a2d6363d1216a319711c3fa92437fa22
Debug:
	UUID: 4a7db079-3516-423c-b741-7370a2164cc1
	SendSystemInformation: False
	SystemInformationVersionPrompt: 4
Keys:
	MapScrollUp: UNKNOWN None
