#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
systemctl --user import-environment DISPLAY
# Activate dbus variables
dbus-update-activation-environment --all
ssh-agent dwm
