#!/bin/sh
# Got 'eem!
# Script to stage and commit my dotfiles and wiki files.

# DOT_CONFIG="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
# DOT_CONFIG="/usr/bin/git --git-dir=$GIT/dotfiles/ --work-tree=$HOME"
WIKI_CONFIG="/usr/bin/git --git-dir=$HOME/Documents/wiki/.wiki/ --work-tree=$HOME/Documents/wiki/"

cd /home/nick/git/dotfiles

cp -rf $HOME/.config $GIT/dotfiles 
cp -rf $HOME/.local/bin $GIT/dotfiles/.local
git add -A
git commit -m "Routine dotfile update"
git push

# $WIKI_CONFIG add $HOME/Documents/wiki/*
# $WIKI_CONFIG commit -m "Routine wiki update"
# $WIKI_CONFIG push
