#!/bin/sh

xrandr \
    --output DP2-1-8 --auto --primary --mode 1920x1080 --rotate normal \
    --output DP2-3 --auto --mode 1920x1080 --rotate normal --right-of DP2-1-8
# xrandr \
#     --output DP1-1 --auto --primary --mode 1920x1080 --rotate normal \
#     --output DP2 --auto --mode 1920x1080 --rotate normal --left-of DP1-1
