#!/bin/sh

xrandr --output eDP1 --auto --primary --mode 1920x1080 --rotate normal --output DP1-2 --auto --mode 1920x1080 --rotate normal --right-of eDP1 --output DP2-1 --auto --mode 1920x1080 --rotate normal --right-of DP1-2
# xrandr \
#     --output eDP1 --auto --primary --mode 1920x1080 --rotate normal \
#     --output DP2 --auto --mode 1920x1080 --rotate normal --right-of eDP1 \
