#!/bin/sh
# Wrapper script for converting markdown files to pdfs
# TODO: Could possibly be an alias

# Remove the file extension from the base name
BASE_FILE="$(echo "$1" | sed 's/\.[^.]*$//')"  
# Specifies where resources are stored
DATA_DIR="$(dirname "$1")" 
if [ -n "$2" ]; then
    DATA_DIR="$2"
fi
pandoc --data-dir="$DATA_DIR" \
    -o "$XDG_DOWNLOAD_DIR"/"$BASE_FILE".pdf \
    "$1"
