#!/bin/sh
# Sets the background

# feh --no-fehbg --bg-scale "$XDG_PICTURES_DIR/wallpaper/Library/trinity3.webp"
feh --no-fehbg --bg-scale "$XDG_PICTURES_DIR/wallpaper/maps/map3.jpg"
# feh --no-fehbg --bg-scale "$XDG_PICTURES_DIR/wallpaper/camping/campfire-forest.jpg"
