#!/usr/bin/env python

import csv, sys
query = sys.argv[1]
acronyms = "/home/nick/dl/acronyms.csv"

with open(acronyms, "r") as f:
    reader = csv.reader(f)
    for row in reader:
        if row[0] == query:
            print(f"{row[0]} | {row[1]}\n    {row[2]}")
            break
