[General]
Dym9PfcodAEyrmNcqaJ63KHDsI4NXEdDbsveti00ZcA%23=1669072838
GeoLocale=system
SensitiveInfoMaskOn=true
autoPlayGif=false
autoScale=false
bForceMaximizeWM=false
blockUntrustedSSLCert=false
captureHDCamera=true
chatListPanelLastWidth=230
conf.webserver=https://us02web.zoom.us
conf.webserver.vendor.default=https://zoom.us
currentMeetingId=84355077350
dR%2BBK01MnhCURMBwWLMT6T7s9knvfnbSAnwvzdE8CPg%23=1669072838
deviceID=9C:B6:D0:98:E1:59
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCloudSwitch=false
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
host.auto.grab.interval=10
isTransCoding=false
logLevel=info
newMeetingWithVideo=true
noSandbox=false
playSoundForNewMessage=false
scaleFactor=1
shareBarTopMargin=0
speaker_volume=190
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
timeFormat12HoursEnable=true
transcodingUI=true
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=nshannon@luc.edu

[AS]
showframewindow=true

[chat.recent]
recentlast.session=

[https%3A]
us02images.zoom.us\p\-1qJbQ0_RJOd40LxewqlNg\ba778693-b1fd-4f39-adc7-220880f3cb67-781=1663638718
us02images.zoom.us\p\-ZLKztd2RYaVPu0p9bw3qQ\99d1b831-76c8-4421-bcd2-8d2e2d0321da-3114=1648147463
us02images.zoom.us\p\0DTItifeS2ScPYoYRxMTrA\508b045c-8f95-4802-8bbd-fbdbf464eeb5-9156=1648147462

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="459,498"
main_frame_pixel_pos_wide="892,889"
