#!/bin/sh

# Launch scripts
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --blocks
$HOME/Scripts/display 

if [ $(xrandr -q | grep " connected " | wc -l) -eq 3 ]; then
    bspc monitor eDP-1 -d I   
    bspc monitor DP-2-2 -d II III IV V VI  
    bspc monitor DP-2-1 -d VII VIII IX X
elif [ $(xrandr -q | grep " connected " | wc -l) -eq 2 ]; then
    bspc monitor eDP-1 -d I   
    bspc monitor DP-2-2 -d II III IV V VI  
else
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

# Wallpaper
#feh --bg-scale "/home/nick/Pictures/Forests/wp3123553-pine-forest-wallpapers.jpg"
feh --bg-scale "/home/nick/Pictures/Mojave/nambung.jpg"

# Status bar
panel &

# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color           "#415e4d" 

# top_padding, right_padding, bottom_padding, left_padding
bspc config border_width         0 
bspc config window_gap          20
bspc config bottom_padding       0
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors   true

# Use below to check for WM_CLASS 
# xprop | grep WM_CLASS

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Steam state=tiled
bspc rule -a steam state=tiled
bspc rule -a Qalculate-gtk state=floating
