#! /bin/sh

# Launch scripts
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/Scripts/refresh.sh

bspc monitor DP-1-2 -d VI VII VIII IX X 
bspc monitor eDP-1 -d I II III IV V 
# bspc monitor -d I II III IV V VI VII VIII IX X

# Wallpaper
feh --bg-fill ~/Pictures/Glacier2021/20210812_015329206_iOS.jpg

# Status bar
panel &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
