#!/bin/sh

# Launch scripts
pgrep -x sxhkd > /dev/null || sxhkd &
#/usr/local/bin/dwmblocks &
$HOME/.config/polybar/launch.sh --blocks
$HOME/.local/bin/monitors

if [ $(xrandr -q | grep " connected " | wc -l) -eq 3 ]; then
    bspc monitor eDP1 -d I   
    bspc monitor DP1-2 -d II III IV V VI  
    bspc monitor DP2-1 -d VII VIII IX X
    #bspc monitor DP1 -d VII VIII IX X
    #bspc monitor DP2-3 -d VII VIII IX X
elif [ $(xrandr -q | grep " connected " | wc -l) -eq 2 ]; then
    bspc monitor eDP1 -d I II III  
    bspc monitor DP1 -d IV V VI VII VIII IX X
else
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

# Wallpaper
feh --bg-scale ~/git/wallpapers/0232.jpg

# Status bar
#panel &
#dwmblocks &

# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color           "#415e4d" 

# top_padding, right_padding, bottom_padding, left_padding
bspc config border_width         1 
bspc config window_gap          15
bspc config bottom_padding       0
bspc config top_padding         35

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors   true

# Use below to check for WM_CLASS 
# xprop | grep WM_CLASS

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Steam state=tiled
bspc rule -a steam state=tiled
bspc rule -a Qalculate-gtk state=floating
