#!bin/sh

xrandr --output DP-2-2 --off --output DP-2-1 --off && xrandr --output eDP-1 --auto --primary --mode 1920x1080 --rotate normal --output DP-2-2 --auto --mode 1920x1080 --rotate normal --right-of eDP-1 --output DP-2-1 --auto --mode 1920x1080 --rotate normal --right-of DP-2-2
#xrandr --output DP-2-2 --off && xrandr --output eDP-1 --auto --primary --mode 1920x1080 --rotate normal --output DP-2-2 --auto --mode 1920x1080 --rotate normal --right-of eDP-1 
#xrandr --output eDP-1 --auto --primary --mode 1920x1080 --rotate normal --output DP-2-2 --auto --mode 1920x1080 --rotate normal --right-of eDP-1 

# Reload
/bin/sh ~/.config/polybar/launch.sh --blocks



